---
title: "title"
author: "author"
abstract: "abstract"
header-includes:
   - \usepackage[brazil]{babel}
   - \usepackage{bm}
   - \usepackage{float}
geometry: left=1.7cm, right=1.7cm, top=3cm, bottom=3cm
output:
  bookdown::pdf_document2:
editor_options:
  chunk_output_type: console
indent: true
---



```{r setup, include=F}
options(digits = 3)  
options(scipen = 999)
ggplot2::theme_set(ggplot2::theme_minimal()) 
knitr::opts_chunk$set(echo=F, message=F, warning=F, fig.pos = 'H', 
                      fig.align = 'center', fig.width = 6, fig.height= 3.5)
scale_fill_discrete = \(...) ggplot2::scale_fill_brewer(... , palette = "Set2") 
library(ggplot2)
library(dplyr)
library(patchwork)
```


```{r}
bar_plot <- function(df, v) {
  ggplot(df, aes(
    x = {{ v }},
    y = prop.table(stat(count)),
    fill =  {{ v }},
    label = scales::percent(prop.table(stat(count)))
  )) +
    geom_bar(position = "dodge", color = "black") +
    geom_text(
      stat = "count",
      position = position_dodge(.9),
      vjust = -0.3,
      size = 3.5
    ) +
    scale_y_continuous(labels = scales::percent) +
    scale_fill_brewer(palette = "Set3", drop = FALSE) +
    labs(y = "Proporção", x = df %>%
      select({{ v }}) %>%
      names()) +
    theme(plot.title = element_text(hjust = 0.5, size = 10))
}


col_plot <- function(df, v) {
  ggplot(df, aes(
    x = {{ v }},
    fill =  {{ v }}
  )) +
    geom_bar(position = "dodge", color = "black") +
    scale_y_continuous(labels = scales::percent) +
    scale_fill_brewer(palette = "Set3", drop = FALSE) +
    labs(y = "Quantidade títulos", x = df %>%
      select({{ v }}) %>%
      names()) +
    theme(plot.title = element_text(hjust = 0.5, size = 10)) +
    coord_flip()
}
```




```{r}
cidades = readr::read_csv('./datas/cidades_gauchas_tratado.csv')
campeonatos = readr::read_csv('./datas/campeonatos_gauchos_tratado.csv')
times = readr::read_csv('./datas/times_gauchos_tratado.csv')
```


\section{Motivação}


```{r}
campeonatos %>% mutate(Primeiro = 
                         case_when(Primeiro != 'Internacional' & 
                                     Primeiro != 'Grêmio' ~ 'Outros',
                                   TRUE ~ Primeiro), 
                       Primeiro = forcats::fct_infreq(Primeiro)) %>%
  bar_plot(Primeiro)
```

\section{Estudo}

```{r}
col_plot(campeonatos %>% 
           mutate(Primeiro = forcats::fct_infreq(Primeiro)), Primeiro)
```



